# Generated by Django 5.2.1 on 2025-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='input_title',
            field=models.CharField(),
        ),
    ]
