# Generated by Django 5.2.1 on 2025-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_deletion_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
