# Generated by Django 5.2.1 on 2025-05-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_token',
        ),
    ]
